// <auto-generated />
// Regenerate: Unity menu Tools → Network → Regenerate message codec registrations

namespace Bw.Injection.Network
{
    public partial class MessageHandlersInstaller
    {
        partial void RegisterGeneratedMessageCodecs(
            System.Collections.Generic.Dictionary<System.Type, Bw.Entities.Network.IMessageReceiver> receivers,
            System.Collections.Generic.Dictionary<System.Type, Bw.Entities.Network.IMessageSender> senders)
        {
            RegisterCodecRouting<Bw.UseCases.TargetedBool, Bw.UseCases.TargetedBoolCodec, Bw.UseCases.TargetedBoolCodecRouting>(receivers, senders);
            RegisterCodec<System.Boolean, Bw.Entities.Network.Codecs.BoolCodec>(receivers, senders);
            RegisterCodec<System.Single, Bw.Entities.Network.Codecs.FloatCodec>(receivers, senders);
            RegisterCodec<System.Int32, Bw.Entities.Network.Codecs.IntCodec>(receivers, senders);
            RegisterCodec<JetBrains.Core.Unit, Bw.Entities.Network.Codecs.UnitCodec>(receivers, senders);
            RegisterCodec<Bw.UseCases.Shooting.Weapon.Network.Requests.ReloadRequestDto, Bw.UseCases.Shooting.Weapon.Network.Requests.ReloadRequestDtoCodec>(receivers, senders);
            RegisterCodec<Bw.UseCases.Shooting.Weapon.Network.Requests.ReloadRequestResultDto, Bw.UseCases.Shooting.Weapon.Network.Requests.ReloadRequestResultDtoCodec>(receivers, senders);
            RegisterCodec<Bw.UseCases.Shooting.Weapon.Network.Requests.ShootRequestDto, Bw.UseCases.Shooting.Weapon.Network.Requests.ShootRequestDtoCodec>(receivers, senders);
            RegisterCodec<Bw.UseCases.Shooting.Weapon.Network.Requests.ShootRequestResultDto, Bw.UseCases.Shooting.Weapon.Network.Requests.ShootRequestResultDtoCodec>(receivers, senders);
        }
    }
}
