// <auto-generated />
// Regenerate: Unity menu Tools → Network → Regenerate message codec registrations

namespace Bw.Injection.Network
{
    public partial class MessageHandlersInstaller
    {
        partial void RegisterGeneratedMessageCodecs(
            System.Collections.Generic.Dictionary<System.Type, Bw.Entities.Network.IMessageReceiver> receivers,
            System.Collections.Generic.Dictionary<System.Type, Bw.Entities.Network.IMessageSender> senders)
        {
            RegisterCodec<System.Boolean, Bw.Entities.Network.Codecs.BoolCodec>(receivers, senders);
            RegisterCodec<Bw.Entities.ClientConnectionState, Bw.Entities.Network.Codecs.ClientConnectionStateCodec>(receivers, senders);
            RegisterCodec<System.Single, Bw.Entities.Network.Codecs.FloatCodec>(receivers, senders);
            RegisterCodec<System.Int32, Bw.Entities.Network.Codecs.IntCodec>(receivers, senders);
            RegisterCodec<JetBrains.Core.Unit, Bw.Entities.Network.Codecs.UnitCodec>(receivers, senders);
            RegisterCodec<Bw.Entities.Network.Prediction.Events.Requests.OutcomeReport<System.Single>, Bw.Entities.Network.Prediction.Events.Codecs.FloatOutcomeReportCodec>(receivers, senders);
            RegisterCodec<Bw.Entities.Network.Prediction.Events.Requests.CausedState<Bw.UseCases.Character.CharacterVitals>, Bw.UseCases.Character.Network.Codecs.CausedVitalsCodec>(receivers, senders);
            RegisterCodec<Bw.Entities.Network.Prediction.Stream.Requests.TickedInput<Bw.UseCases.Movement.MovementInput>, Bw.UseCases.Movement.Network.Codecs.TickedMovementInputCodec>(receivers, senders);
            RegisterCodec<Bw.Entities.Network.Prediction.Stream.Requests.TickedState<Bw.UseCases.Movement.MovementState>, Bw.UseCases.Movement.Network.Codecs.TickedMovementStateCodec>(receivers, senders);
            RegisterCodec<Bw.Entities.Network.Prediction.Stream.Requests.TickedInput<Bw.UseCases.Shooting.Weapon.WeaponInput>, Bw.UseCases.Shooting.Weapon.Network.Codecs.TickedWeaponInputCodec>(receivers, senders);
            RegisterCodec<Bw.Entities.Network.Prediction.Stream.Requests.TickedState<Bw.UseCases.Shooting.Weapon.WeaponState>, Bw.UseCases.Shooting.Weapon.Network.Codecs.TickedWeaponStateCodec>(receivers, senders);
        }
    }
}
