using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using UnityEditor;
using UnityEditor.Compilation;
using UnityEngine;
using Assembly = System.Reflection.Assembly;

namespace Bw.EditorTools.Network
{
    /// <summary>
    /// Scans player assemblies for <c>struct</c> types implementing <c>ICodec&lt;T&gt;</c> and
    /// <c>class</c> types deriving from <c>CodecTargetRouting&lt;TCodec&gt;</c>, then regenerates
    /// <c>MessageHandlersInstaller.Generated.cs</c>.
    /// </summary>
    public static class MessageHandlersCodegen
    {
        private const string MenuPath = "Tools/Network/Regenerate message codec registrations";

        private const string CodecOpenGenericName = "ICodec`1";
        private const string CodecRoutingOpenGenericName = "CodecTargetRouting`1";
        private const string NetworkSerializableFullName = "Unity.Netcode.INetworkSerializable";

        private static readonly string OutputPath = Path.Combine(
            Application.dataPath,
            "Game",
            "Scripts",
            "Injection",
            "Network",
            "MessageHandlersInstaller.Generated.cs");

        [MenuItem(MenuPath)]
        public static void Regenerate()
        {
            if (EditorApplication.isCompiling)
            {
                Debug.LogWarning("MessageHandlersCodegen: compilation in progress, try again when it finishes.");
                return;
            }

            var codecInterface = ResolveOpenGenericDefinition(CodecOpenGenericName);
            if (codecInterface == null)
            {
                Debug.LogError("MessageHandlersCodegen: could not resolve ICodec`1.");
                return;
            }

            var routingBase = ResolveOpenGenericDefinition(CodecRoutingOpenGenericName);
            if (routingBase == null)
                Debug.LogWarning("MessageHandlersCodegen: could not resolve CodecTargetRouting`1; routings will be skipped.");

            var pairs = DiscoverCodecPairs(codecInterface);
            if (pairs.Count == 0)
            {
                Debug.LogWarning("MessageHandlersCodegen: no ICodec<> implementations found.");
                return;
            }

            var routingByCodec = routingBase != null
                ? DiscoverRoutingByCodec(pairs, routingBase)
                : new Dictionary<Type, Type>();

            var ordered = pairs
                .OrderByDescending(p => routingByCodec.ContainsKey(p.codecType))
                .ThenBy(p => p.codecType.FullName, StringComparer.Ordinal)
                .ToList();

            var sb = new StringBuilder(1024);
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("// Regenerate: Unity menu Tools → Network → Regenerate message codec registrations");
            sb.AppendLine();
            sb.AppendLine("namespace Bw.Injection.Network");
            sb.AppendLine("{");
            sb.AppendLine("    public partial class MessageHandlersInstaller");
            sb.AppendLine("    {");
            sb.AppendLine("        partial void RegisterGeneratedMessageCodecs(");
            sb.AppendLine("            System.Collections.Generic.Dictionary<System.Type, Bw.Entities.Network.IMessageReceiver> receivers,");
            sb.AppendLine("            System.Collections.Generic.Dictionary<System.Type, Bw.Entities.Network.IMessageSender> senders)");
            sb.AppendLine("        {");

            foreach (var (valueType, codecType) in ordered)
            {
                if (routingByCodec.TryGetValue(codecType, out var routingType))
                {
                    sb.AppendLine(
                        $"            RegisterCodecRouting<{TypeSpec(valueType)}, {TypeSpec(codecType)}, {TypeSpec(routingType)}>(receivers, senders);");
                }
                else
                {
                    sb.AppendLine(
                        $"            RegisterCodec<{TypeSpec(valueType)}, {TypeSpec(codecType)}>(receivers, senders);");
                }
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(OutputPath, sb.ToString(), new UTF8Encoding(false));
            AssetDatabase.Refresh();

            var routingCount = ordered.Count(p => routingByCodec.ContainsKey(p.codecType));
            Debug.Log(
                $"MessageHandlersCodegen: wrote {ordered.Count} codec(s) ({routingCount} with routing) to {OutputPath}");
        }

        private static string TypeSpec(Type t) =>
            t.IsNested
                ? $"{TypeSpec(t.DeclaringType!)}.{t.Name}"
                : string.IsNullOrEmpty(t.Namespace)
                    ? t.Name
                    : $"{t.Namespace}.{t.Name}";

        private static IEnumerable<Assembly> GetCandidateAssemblies()
        {
            var seen = new HashSet<string>(StringComparer.Ordinal);
            var list = new List<Assembly>();

            void TryAdd(Assembly? assembly)
            {
                if (assembly == null || assembly.IsDynamic)
                    return;
                var name = assembly.GetName().Name;
                if (string.IsNullOrEmpty(name) || !seen.Add(name))
                    return;
                if (ShouldSkipAssembly(name))
                    return;
                list.Add(assembly);
            }

            foreach (var playerAsm in CompilationPipeline.GetAssemblies(AssembliesType.Player))
                TryAdd(AppDomain.CurrentDomain.GetAssemblies().FirstOrDefault(a => a.GetName().Name == playerAsm.name));

            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
                TryAdd(assembly);

            return list;
        }

        private static bool ShouldSkipAssembly(string name) =>
            name.StartsWith("Unity.", StringComparison.Ordinal) ||
            name.StartsWith("UnityEngine.", StringComparison.Ordinal) ||
            name.StartsWith("System.", StringComparison.Ordinal) ||
            name.StartsWith("mscorlib", StringComparison.Ordinal) ||
            name.StartsWith("netstandard", StringComparison.Ordinal) ||
            name.StartsWith("Mono.", StringComparison.Ordinal) ||
            name == "Zenject" ||
            name == "JetBrains.Lifetimes" ||
            name == "nunit.framework" ||
            name == "Extenject" ||
            name.EndsWith(".Editor", StringComparison.Ordinal);

        private static Type? ResolveOpenGenericDefinition(string openGenericName)
        {
            foreach (var assembly in GetCandidateAssemblies())
            {
                foreach (var type in SafeGetTypes(assembly))
                {
                    if (type.IsGenericTypeDefinition && type.Name == openGenericName)
                        return type;
                }
            }

            return null;
        }

        private static bool ImplementsInterfaceByFullName(Type type, string interfaceFullName)
        {
            if (type.FullName == interfaceFullName)
                return true;

            foreach (var it in type.GetInterfaces())
            {
                if (it.FullName == interfaceFullName)
                    return true;
            }

            return false;
        }

        private static Type? GetRoutingCodecType(Type routingType, Type routingBaseDefinition)
        {
            for (var current = routingType; current != null; current = current.BaseType)
            {
                if (!current.IsGenericType)
                    continue;
                var def = current.GetGenericTypeDefinition();
                if (def != routingBaseDefinition)
                    continue;
                var args = current.GetGenericArguments();
                return args.Length == 1 ? args[0] : null;
            }

            return null;
        }

        private static List<(Type valueType, Type codecType)> DiscoverCodecPairs(Type codecInterface)
        {
            var results = new List<(Type valueType, Type codecType)>();
            var seenValues = new Dictionary<Type, Type>();

            foreach (var assembly in GetCandidateAssemblies())
            {
                foreach (var type in SafeGetTypes(assembly))
                {
                    if (!type.IsValueType || type.IsEnum || type.IsAbstract)
                        continue;

                    if (!ImplementsInterfaceByFullName(type, NetworkSerializableFullName))
                        continue;

                    Type? valueType = null;
                    foreach (var iface in type.GetInterfaces())
                    {
                        if (!iface.IsGenericType || iface.GetGenericTypeDefinition() != codecInterface)
                            continue;
                        var args = iface.GetGenericArguments();
                        if (args.Length != 1)
                            continue;
                        valueType = args[0];
                        break;
                    }

                    if (valueType == null)
                        continue;

                    if (seenValues.TryGetValue(valueType, out var existing) && existing != type)
                    {
                        throw new InvalidOperationException(
                            $"Two codecs for payload {valueType.FullName}: {existing.FullName} and {type.FullName}.");
                    }

                    seenValues[valueType] = type;
                    results.Add((valueType, type));
                }
            }

            return results;
        }

        private static Dictionary<Type, Type> DiscoverRoutingByCodec(
            List<(Type valueType, Type codecType)> pairs,
            Type routingBaseDefinition)
        {
            var knownCodecs = new HashSet<Type>(pairs.Select(p => p.codecType));
            var map = new Dictionary<Type, Type>();

            foreach (var assembly in GetCandidateAssemblies())
            {
                foreach (var type in SafeGetTypes(assembly))
                {
                    if (type.IsAbstract || type.IsInterface || type.IsValueType)
                        continue;

                    var codecType = GetRoutingCodecType(type, routingBaseDefinition);
                    if (codecType == null || !knownCodecs.Contains(codecType))
                        continue;

                    if (map.TryGetValue(codecType, out var existing) && existing != type)
                    {
                        throw new InvalidOperationException(
                            $"Two routings for codec {codecType.FullName}: {existing.FullName} and {type.FullName}.");
                    }

                    map[codecType] = type;
                }
            }

            return map;
        }

        private static IEnumerable<Type> SafeGetTypes(Assembly assembly)
        {
            try
            {
                return assembly.GetTypes();
            }
            catch (ReflectionTypeLoadException e)
            {
                return e.Types.Where(t => t != null).Cast<Type>();
            }
            catch
            {
                return Array.Empty<Type>();
            }
        }
    }
}
