using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Bw.EditorTools.Network
{
    /// <summary>
    /// Scans loaded assemblies for <c>struct</c> types implementing <c>ICodec&lt;T&gt;</c> and
    /// <c>INetworkSerializable</c>, then regenerates <c>MessageHandlersInstaller.Generated.cs</c>.
    /// Uses type names only so this editor script does not need references to game assemblies.
    /// </summary>
    public static class MessageHandlersCodegen //TODO: roslin code generator вместо рефлексии с юнити для регенерации кодеков на этапе компиляции.
    {
        private const string MenuPath = "Tools/Network/Regenerate message codec registrations";

        private const string CodecOpenGenericFullName = "Bw.Entities.Network.ICodec`1";
        private const string NetworkSerializableFullName = "Unity.Netcode.INetworkSerializable";

        private static readonly string OutputPath = Path.Combine(
            Application.dataPath,
            "Scripts",
            "Injection",
            "Network",
            "MessageHandlersInstaller.Generated.cs");

        [MenuItem(MenuPath)]
        public static void Regenerate()
        {
            var pairs = DiscoverCodecPairs();
            if (pairs.Count == 0)
            {
                Debug.LogWarning("MessageHandlersCodegen: no ICodec<> implementations found.");
                return;
            }

            var sb = new StringBuilder(1024);
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("// Regenerate: Unity menu Tools → Network → Regenerate message codec registrations");
            sb.AppendLine();
            sb.AppendLine("namespace Bw.Injection.Network");
            sb.AppendLine("{");
            sb.AppendLine("    public partial class MessageHandlersInstaller");
            sb.AppendLine("    {");
            sb.AppendLine("        partial void RegisterGeneratedMessageCodecs(");
            sb.AppendLine("            System.Collections.Generic.Dictionary<System.Type, Bw.Entities.Network.IMessageReceiver> receivers,");
            sb.AppendLine("            System.Collections.Generic.Dictionary<System.Type, Bw.Entities.Network.IMessageSender> senders)");
            sb.AppendLine("        {");

            foreach (var (valueType, codecType) in pairs)
                sb.AppendLine(
                    $"            RegisterCodec<{TypeSpec(valueType)}, {TypeSpec(codecType)}>(receivers, senders);");

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(OutputPath, sb.ToString(), new UTF8Encoding(false));
            AssetDatabase.Refresh();
            Debug.Log($"MessageHandlersCodegen: wrote {pairs.Count} codec(s) to {OutputPath}");
        }

        private static string TypeSpec(Type t) =>
            t.IsNested
                ? $"{TypeSpec(t.DeclaringType!)}.{t.Name}"
                : string.IsNullOrEmpty(t.Namespace)
                    ? t.Name
                    : $"{t.Namespace}.{t.Name}";

        private static Type? ResolveOpenGenericInterface(string fullName)
        {
            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                if (assembly.IsDynamic)
                    continue;
                var t = assembly.GetType(fullName, throwOnError: false, ignoreCase: false);
                if (t != null)
                    return t;
            }

            return null;
        }

        private static bool ImplementsInterfaceByFullName(Type type, string interfaceFullName)
        {
            if (type.FullName == interfaceFullName)
                return true;

            foreach (var it in type.GetInterfaces())
            {
                if (it.FullName == interfaceFullName)
                    return true;
            }

            return false;
        }

        private static List<(Type valueType, Type codecType)> DiscoverCodecPairs()
        {
            var results = new List<(Type valueType, Type codecType)>();
            var codecInterface = ResolveOpenGenericInterface(CodecOpenGenericFullName);
            if (codecInterface == null)
            {
                Debug.LogError(
                    $"MessageHandlersCodegen: could not resolve '{CodecOpenGenericFullName}'. Is the runtime assembly loaded?");
                return results;
            }

            var seenValues = new Dictionary<Type, Type>();

            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                if (assembly.IsDynamic)
                    continue;

                var name = assembly.GetName().Name ?? "";
                if (name.StartsWith("Unity.", StringComparison.Ordinal) ||
                    name.StartsWith("System.", StringComparison.Ordinal) ||
                    name.StartsWith("mscorlib", StringComparison.Ordinal) ||
                    name.StartsWith("netstandard", StringComparison.Ordinal) ||
                    name.StartsWith("Mono.", StringComparison.Ordinal) ||
                    name == "Zenject" ||
                    name == "JetBrains.Lifetimes" ||
                    name == "nunit.framework")
                    continue;

                Type[] types;
                try
                {
                    types = assembly.GetTypes();
                }
                catch (ReflectionTypeLoadException e)
                {
                    types = e.Types.Where(t => t != null).Cast<Type>().ToArray();
                }
                catch
                {
                    continue;
                }

                foreach (var type in types)
                {
                    if (!type.IsValueType || type.IsEnum || type.IsAbstract)
                        continue;

                    if (!ImplementsInterfaceByFullName(type, NetworkSerializableFullName))
                        continue;

                    Type? valueType = null;
                    foreach (var iface in type.GetInterfaces())
                    {
                        if (!iface.IsGenericType || iface.GetGenericTypeDefinition() != codecInterface)
                            continue;
                        var args = iface.GetGenericArguments();
                        if (args.Length != 1)
                            continue;
                        valueType = args[0];
                        break;
                    }

                    if (valueType == null)
                        continue;

                    if (seenValues.TryGetValue(valueType, out var existing) && existing != type)
                        throw new InvalidOperationException(
                            $"Two codecs for payload {valueType.FullName}: {existing.FullName} and {type.FullName}.");

                    seenValues[valueType] = type;
                    results.Add((valueType, codecType: type));
                }
            }

            results.Sort((a, b) => string.Compare(a.codecType.FullName, b.codecType.FullName, StringComparison.Ordinal));
            return results;
        }
    }
}
